# Generated by Django 4.0.6 on 2022-07-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway_app', '0002_payment_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_detail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
