# Generated by Django 4.0.6 on 2022-08-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway_app', '0003_alter_payment_detail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
