# Generated by Django 4.0.6 on 2022-08-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway_app', '0004_product_image_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment_detail',
            new_name='paymentDetail',
        ),
    ]
